#!/usr/bin/env sh

# Run a command as root: if the current user is root, run the command directly,
# otherwise prefix it with sudo.

SUDO=''
if [ "$(id -u)" -ne 0 ]
then
    SUDO='sudo -E'
fi

$SUDO PATH="$PATH" "$@"