name: Fork-specific CI

on:
  push:
    branches:
      - "**"

permissions:
  checks: write
  pull-requests: write

jobs:
  full:
    if: github.repository != 'facebook/bpfilter'
    strategy:
      fail-fast: false
      matrix:
        # This forces GitHub to print "fedora:40, x64" in the job name.
        system: ["fedora:40"]
        arch: ["X64"]
        mode: ["release", "debug"]
    container: "${{ matrix.system }}"
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies (Fedora)
        run: |
          sudo dnf --disablerepo=* --enablerepo=fedora,updates --setopt=install_weak_deps=False -y install \
            bison \
            bpftool \
            clang \
            clang-tools-extra \
            cmake \
            doxygen \
            flex \
            git \
            lcov \
            libasan \
            libbpf-devel \
            libcmocka-devel \
            libnl3-devel \
            libubsan \
            python3-breathe \
            python3-furo \
            python3-sphinx \
            pkgconf
      - name: Configure build
        run: cmake -S $GITHUB_WORKSPACE -B $GITHUB_WORKSPACE/build -DCMAKE_BUILD_TYPE=${{ matrix.mode }}
      - name: Build
        run: make -C $GITHUB_WORKSPACE/build
      # Skip unit tests, the GitHub-hosted runners' kernel is too old.
      # Skip coverage as unit tests are not run.
      - name: Check style
        run: make -C $GITHUB_WORKSPACE/build checkstyle
      - name: Generate documentation
        run: make -C $GITHUB_WORKSPACE/build doc
