name: Testing on CI

on:
  push:
    branches:
      - "**"

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  create-container:
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/facebook/bpfilter/fedora:41
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
      - name: Get tags
        run: echo "${{ steps.meta.outputs.tags }}"
      - name: Get labels
        run: echo "${{ steps.meta.outputs.labels }}"

  build:
    needs: create-container
    strategy:
      fail-fast: false
      matrix:
        host: ["ubuntu-latest", "4-core-ubuntu-arm"]
    runs-on: ["${{matrix.host}}"]
    container: ghcr.io/facebook/bpfilter/fedora:41
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure build
        run: cmake -S $GITHUB_WORKSPACE -B $GITHUB_WORKSPACE/build -DCMAKE_BUILD_TYPE=debug
      - name: Build
        run: make -C $GITHUB_WORKSPACE/build -j `nproc` bpfilter libbpfilter bfcli

  test:
    needs: create-container
    container: ghcr.io/facebook/bpfilter/fedora:41
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure build
        run: cmake -S $GITHUB_WORKSPACE -B $GITHUB_WORKSPACE/build -DCMAKE_BUILD_TYPE=debug
      - name: Build
        run: make -C $GITHUB_WORKSPACE/build -j `nproc` test

  checkstyle:
    needs: create-container
    container: ghcr.io/facebook/bpfilter/fedora:41
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure build
        run: cmake -S $GITHUB_WORKSPACE -B $GITHUB_WORKSPACE/build -DCMAKE_BUILD_TYPE=debug
      - name: Build
        run: make -C $GITHUB_WORKSPACE/build -j `nproc` check

  documentation:
    needs: create-container
    container: ghcr.io/facebook/bpfilter/fedora:41
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure build
        run: cmake -S $GITHUB_WORKSPACE -B $GITHUB_WORKSPACE/build -DCMAKE_BUILD_TYPE=debug
      - name: Build
        run: make -C $GITHUB_WORKSPACE/build -j `nproc` doc
